<?php
/* @var $this \Zend\View\Renderer\PhpRenderer */
Use Core\ViewHelper\ConfigHelper;
$title = 'Adm - ACL Manager';
$this->headTitle($title);
?>
<?php
$this->inlineScript ()->prependFile ( $this->configHelper(ConfigHelper::CDN_PLACEDESFRANCHISES) . '/js/administration/admin-user.js' );
?>

<h2 class="page-header"><?php echo $this->escapeHtml($title); ?></h2>
<?php
$form->setAttribute ( 'class', 'form-horizontal' );
$form->setAttribute ( 'action', $this->url ( 'admin/aclmanager', array (
		'action' => 'add' 
) ) )->prepare ();?>
<?php $this->form($form, \TwbBundle\Form\View\Helper\TwbBundleForm::LAYOUT_HORIZONTAL);?>
<?php echo $this->form ()->openTag ( $form );?>
<?php echo $this->formRow ( $form->get ( 'username' ) );?>
<?php echo $this->formRow ( $form->get ( 'email' ) );?>
<?php echo $this->formRow ( $form->get ( 'password' ) );?>
<?php echo $this->formRow ( $form->get ( 'role' ) );?>
<?php echo $this->formRow ( $form->get ( 'soumettre' ) );?>
<?php echo $this->form ()->closeTag ( $form );?>

