<?php
/**
 * Configuration file generated by ZFTool
 * The previous configuration file is stored in application.config.old
 *
 * @see https://github.com/zendframework/ZFTool
 */
$config = array (
		'modules' => array (
				'DoctrineModule',
				'DoctrineORMModule',
				'ModuleLayouts',
				'ZfcBase',
				'ZfcUser',
				'ZfcUserDoctrineORM',
				'Core',
				'Application',
				'RestClient',
				'TwbBundle', 
		),
		'module_listener_options' => array (
				'module_paths' => array (
						'./module',
						'./vendor' 
				),
				'config_glob_paths' => array (
						'config/autoload/{,*.}{global,local}.php' 
				) 
		) 
);

return $config;


