<?php
/* @var $this \Zend\View\Renderer\PhpRenderer */
Use Core\ViewHelper\ConfigHelper;
$cdn_placedesfranchises = $this->configHelper(ConfigHelper::CDN_TRADUCTEUR);
?>
<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <?php if ($this->headTitle()->renderTitle() == ''): ?>
        <title>Traducteur Abréviations Fusacq</title>
    <?php else: ?>
        <?php echo $this->headTitle()->setAutoEscape(false); ?>
    <?php endif; ?>

    <!-- Le styles -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/logo-trdt.png'))
        ->prependStylesheet($this->basePath('css/style.css'))
        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ->prependStylesheet($this->basePath('css/customize.css'))?>

    <!-- Scripts -->
    <?php echo $this->headScript()
        ->prependFile($this->basePath('js/bootstrap.min.js'))
        ->prependFile($this->basePath('js/jquery.min.js'))
        ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
        ->prependFile($this->basePath('js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
    ; ?>

</head>
<body>
<div class="container">
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="#">DCO FUSACQ</a>
            </div>
            <ul class="nav navbar-nav">
                <li class="active"><a href="#">ACCUEL</a></li>
                <li><a href="#">AJOUTER</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-center" style="margin-left: 20px;">
                <li ><a style="color: #999;">RECHERCHER :</a></li>
                <li style="position: relative; right: 22px;">
                    <form class="navbar-form navbar-left" role="search">
                        <div class="form-group">
                            <input type="text" class="form-control" placeholder="Search">
                        </div>
                        <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-search"></span></button>
                        <div style="display: inline-block; float: right; position: relative; bottom: 5px; margin-left: 5px;">
                            <input type="radio"  value="abv" style="position: relative; top: 4px;"> <span style="color: #999; position: relative; top: 2px;">ABV</span> <br/>
                            <input type="radio"  value="abv" style="position: relative; bottom: 1px;"> <span style="color: #999; position: relative; bottom: 1px;">ITEM</span>
                        </div>
                    </form>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right" style="margin-right: 10px;">
                <li><a href=<?php echo $this->url('application/usermanagement'); ?>><span class="glyphicon glyphicon-user"></span> UTILISATEURS</a></li>
                <li><a href="#"><span class="glyphicon glyphicon-log-in"></span> DECONNEXION</a></li>
            </ul>
        </div>
    </nav>
</div>
<div class="container">

    <div class="content" style="width: 100%; height: 600px; margin: 0 auto; background-color: #EEEEF4;">
        <div style="text-align: center; padding-top: 20px;" class="nav">
            <div class="btn-group" role="group">
                <button class="btn btn-default">
                    <a href="#">A</a>
                </button>
                <button class="btn btn-default">
                    <a href="#">B</a>
                </button>
                <button class="btn btn-default">
                    <a href="#">C</a>
                </button>
                <button class="btn btn-default">
                    <a href="#">D</a>
                </button>
                <button class="btn btn-default">
                    <a href="#">E</a>
                </button>
                <button class="btn btn-default">
                    <a href="#">F</a>
                </button>
                <button class="btn btn-default">
                    <a href="#">G</a>
                </button>
                <button class="btn btn-default">
                    <a href="#">H</a>
                </button>
                <button class="btn btn-default">
                    <a href="#">I</a>
                </button>
                <button class="btn btn-default">
                    <a href="#">J</a>
                </button>
                <button class="btn btn-default">
                    <a href="#">K</a>
                </button>
                <button class="btn btn-default">
                    <a href="#">L</a>
                </button>
                <button class="btn btn-default">
                    <a href="#">M</a>
                </button>
                <button class="btn btn-default">
                    <a href="#">N</a>
                </button>
                <button class="btn btn-default">
                    <a href="#">O</a>
                </button>
                <button class="btn btn-default">
                    <a href="#">P</a>
                </button>
                <button class="btn btn-default">
                    <a href="#">Q</a>
                </button>
                <button class="btn btn-default">
                    <a href="#">R</a>
                </button>
                <button class="btn btn-default">
                    <a href="#">S</a>
                </button>
                <button class="btn btn-default">
                    <a href="#">T</a>
                </button>
                <button class="btn btn-default">
                    <a href="#">U</a>
                </button>
                <button class="btn btn-default">
                    <a href="#">V</a>
                </button>
                <button class="btn btn-default">
                    <a href="#">W</a>
                </button>
                <button class="btn btn-default">
                    <a href="#">X</a>
                </button>
                <button class="btn btn-default">
                    <a href="#">Y</a>
                </button>
                <button class="btn btn-default">
                    <a href="#">Z</a>
                </button>
            </div>
        </div>
        <div id="page-wrapper" style="padding-top: 50px; margin-left: 30px; margin-right: 30px;">
            <?php echo $this->content; ?>
        </div>
    </div>
    <hr>
    <footer style="text-align: center">
        <div class="container">
            <p class="text-muted">&copy;<?php echo date('Y') ?> Dictionaire Fusacq Tous Droits réservés</p>
        </div>
    </footer>
</div> <!-- /container -->
<?php echo $this->inlineScript() ?>
</body>
</html>
