<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <?php if ($this->headTitle()->renderTitle() == ''): ?>
        <title>Traducteur Abréviations Fusacq</title>
    <?php else: ?>
        <?php echo $this->headTitle()->setAutoEscape(false); ?>
    <?php endif; ?>

    <!-- Le styles -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/logo-trdt.png'))
        ->prependStylesheet($this->basePath('css/style.css'))
        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
    ;?>

    <!-- Scripts -->
    <?php echo $this->headScript()
        ->prependFile($this->basePath('js/bootstrap.min.js'))
        ->prependFile($this->basePath('js/jquery.min.js'))
        ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
        ->prependFile($this->basePath('js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
    ; ?>

</head>
<body>
<div class="container">
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header" style="font-weight: bold">
                <a class="navbar-brand" href=<?php echo $this->url('home'); ?>>DICO FUSACQ</a>
            </div>
            <ul class="nav navbar-nav">
                <li class="active"><a href=<?php echo $this->url('home'); ?>>ACCUEL</a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">GESTION DU DICTIONAIRE <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li class="gestion-dico"><a href=<?php echo $this->url('addabreviation'); ?>>AJOUTER UN ITEME</a></li>
                        <li><a href="#">AUTRE ACTION</a></li>
                        <li role="separator" class="divider"></li>
                    </ul>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-center" style="margin-left: 5px;">
                <li style="">
                    <form class="navbar-form navbar-left" role="search" method="post" action="<?php echo $this->url('searchabreviation'); ?>">
                        <div class="form-group">
                            <input type="text" name="mot_cle" class="form-control" placeholder="Rechercher">
                        </div>
                        <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-search"></span></button>
                        <div style="display: inline-block; float: right; position: relative; bottom: 5px; margin-left: 5px;">
                            <input type="radio"  name="critere_recherche" value="iteme" checked style="position: relative; top: 3px;"> <span style="color: #999; position: relative; top: 1px;">ITEME</span> <br/>
                            <input type="radio"  name="critere_recherche" value="terme" style="position: relative; bottom: 3px;"> <span style="color: #999; position: relative; bottom: 3px;">TERME</span>
                        </div>
                    </form>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right" style="margin-right: 5px;">
                <li class = 'admin-user'>
                    <a href=<?php echo $this->url('application/usermanagement'); ?>>
                        <span class="glyphicon glyphicon-user"></span> UTILISATEURS
                    </a>
                </li>
                <li><a href="/user/logout"><span class="glyphicon glyphicon-log-in"></span> DECONNEXION</a></li>
            </ul>
        </div>
    </nav>
</div>
<div class="container">

    <div class="content" style="width: 100%; height: 650px; margin: 0 auto; background-color: #EEEEF4;">

        <div id="page-wrapper" style="height:650px;  padding-top: 10px; margin-left: 30px; margin-right: 30px;">
            <?php echo $this->content; ?>
        </div>
    </div>
    <hr>
    <footer style="text-align: center">
        <div class="container">
            <p class="text-muted">&copy;<?php echo date('Y') ?> Dictionaire Fusacq Tous Droits réservés</p>
        </div>
    </footer>
</div> <!-- /container -->
<?php echo $this->inlineScript() ?>
</body>
</html>