<div style="width: 100%; height: 380px; margin: 0 auto; text-align: center" class="jumbotron vertical-center">
    <div style="margin-top: 50px; margin-bottom: 10px;">
        <h3>Ajouter une abréviation avec sa traduction</h3>
        <form class="form-inline">
            <div class="form-group">
                <label class="sr-only" for="abreviation">Abréviation</label>
                <input type="text" class="form-control" id="abreviation" placeholder="Abréviation">
            </div>
            <div class="form-group">
                <label class="sr-only" for="traduction">Traduction</label>
                <input type="text" class="form-control" id="traduction" placeholder="Traduction">
            </div>
            <button type="submit" class="btn btn-default">Ajouter</button>
        </form>
    </div>
    <a href="">Afficher le dictionaire</a>
</div>
