<style>
    .btn-default{
        color: #009cd7;
        font-weight: bold;
    }
</style>

<?php
/* @var $this \Zend\View\Renderer\PhpRenderer */
Use Core\ViewHelper\ConfigHelper;
$this->inlineScript ()->prependFile ( $this->configHelper(ConfigHelper::CDN_TRADUCTEUR) . 'plugins/bootbox/bootbox.min.js' );
$this->inlineScript ()->prependFile ( $this->configHelper(ConfigHelper::CDN_TRADUCTEUR) . 'js/application/admin-dico.js' );
?>
<div style="text-align: center; padding-top: 10px;" id="idMenuAlphabet">
    <div class="btn-group" role="group">
        <a href="<?php echo $this->url('searchabreviation'); ?>?letter=a" class="btn btn-default" style="color: #009cd7">
            A
        </a>
        <a href="<?php echo $this->url('searchabreviation'); ?>?letter=b" class="btn btn-default">
            B
        </a>
        <a href="<?php echo $this->url('searchabreviation'); ?>?letter=c" class="btn btn-default">
           C
        </a>
        <a href="<?php echo $this->url('searchabreviation'); ?>?letter=d" class="btn btn-default">
            D
        </a>
        <a href="<?php echo $this->url('searchabreviation'); ?>?letter=e" class="btn btn-default">
            E
        </a>
        <a href="<?php echo $this->url('searchabreviation'); ?>?letter=f" class="btn btn-default">
            F
        </a>
        <a href="<?php echo $this->url('searchabreviation'); ?>?letter=g" class="btn btn-default">
            G
        </a>
        <a href="<?php echo $this->url('searchabreviation'); ?>?letter=h" class="btn btn-default">
            H
        </a>
        <a href="<?php echo $this->url('searchabreviation'); ?>?letter=i" class="btn btn-default">
            I
        </a>
        <a href="<?php echo $this->url('searchabreviation'); ?>?letter=j" class="btn btn-default">
            J
        </a>
        <a href="<?php echo $this->url('searchabreviation'); ?>?letter=k" class="btn btn-default">
            K
        </a>
        <a href="<?php echo $this->url('searchabreviation'); ?>?letter=l" class="btn btn-default">
            L
        </a>
        <a href="<?php echo $this->url('searchabreviation'); ?>?letter=m" class="btn btn-default">
           M
        </a>
        <a href="<?php echo $this->url('searchabreviation'); ?>?letter=n" class="btn btn-default">
            N
        </a>
        <a href="<?php echo $this->url('searchabreviation'); ?>?letter=o" class="btn btn-default">
            O
        </a>
        <a href="<?php echo $this->url('searchabreviation'); ?>?letter=p" class="btn btn-default">
            P
        </a>
        <a href="<?php echo $this->url('searchabreviation'); ?>?letter=q" class="btn btn-default">
            Q
        </a>
        <a href="<?php echo $this->url('searchabreviation'); ?>?letter=r" class="btn btn-default">
            R
        </a>
        <a href="<?php echo $this->url('searchabreviation'); ?>?letter=s" class="btn btn-default">
            S
        </a>
        <a href="<?php echo $this->url('searchabreviation'); ?>?letter=t" class="btn btn-default">
            T
        </a>
        <a href="<?php echo $this->url('searchabreviation'); ?>?letter=u" class="btn btn-default">
            U
        </a>
        <a href="<?php echo $this->url('searchabreviation'); ?>?letter=v" class="btn btn-default">
            V
        </a>
        <a href="<?php echo $this->url('searchabreviation'); ?>?letter=w" class="btn btn-default">
            W
        </a>
        <a href="<?php echo $this->url('searchabreviation'); ?>?letter=x" class="btn btn-default">
            X
        </a>
        <a href="<?php echo $this->url('searchabreviation'); ?>?letter=y" class="btn btn-default">
            Y
        </a>
        <a href="<?php echo $this->url('searchabreviation'); ?>?letter=z" class="btn btn-default">
            Z
        </a>
    </div>
</div>
<div class="row" style="width: 70%; margin: 0 auto; margin-top: 50px;">
 	<?php if(count($this->paginator) > 0) :?>
    <div class="panel panel-default">
	    <table class="table table-bordered">
	        <thead>
	        <tr >
	            <th class="text-center" style="background-color: #2e2e2e; color:#ffffff"> Iteme</th>
	            <th class="text-center" style="background-color: #2e2e2e; color:#ffffff">Traduction</th>
                <th class="text-center" style="background-color: #2e2e2e; color:#ffffff">Modifier</th>
                <th class="text-center" style="background-color: #2e2e2e; color:#ffffff">Supprimer</th>
	        </tr>
	        </thead>
	        <tbody>
	       
		        <?php foreach ($this->paginator as $abreviation) : ?>
		            <tr class="text-center" style="width: 60%">
		                <td style="width: 100px; font-size: 15px; font-family: 'interstateregular'; "><?php echo $this->escapeHtml($abreviation->iteme);?></td>
		                <td style=" width: 100px; font-size: 15px; font-family: 'interstateregular'; "><?php echo $this->escapeHtml($abreviation->traduction);?></td>
		                <td style="width: 100px">
		                    <a href="<?php echo $this->url('editabreviation'); ?>?id=<?php echo $abreviation->id;?>" class="btn btn-warning btn-xs" aria-label="Left Align">
		                        <span class="glyphicon glyphicon-edit" aria-hidden="true" style="color: #ffffff"></span>
		                    </a>
		                </td>
		                <td style="width: 100px;">
		                    <a href="<?php echo $this->url('deleteabreviation'); ?>" class="btn btn-danger js-btn-danger btn-xs" aria-label="Left Align" id-iteme = "<?php echo $abreviation->id ?>">
		                            <span class="glyphicon glyphicon-trash" aria-hidden="true" style="color: #ffffff"></span>
		                    </a>
		                </td>
		
		            </tr>
		        <?php endforeach; ?>
		   
	        </tbody>
	    </table>
    </div>
   <?php elseif(count($this->flashMessages) > 0):
   			foreach ($this->flashMessages as $msg):
   	?>
            <p> <span class='erreur'>  <?php echo $msg; ?>  </span > </p>
    <?php 
    		endforeach;
    	else :
    ?>
            <p > <span class='erreur'>  Le dictionaire est vide  </span > </p>                                   
	    	
   <?php endif;?>

    <div style="width:60%; position: absolute; bottom: 10px; text-align: center;">
        <div class="">
            <?php
            // add at the end of the file after the table
            echo $this->paginationControl(
// the paginator object
                $this->paginator,
                // the scrolling style
                'sliding',
                // the partial to use to render the control
                'paginator.phtml',
                // the route to link to when a user clicks a control link
                array(
                    'route' => 'lead',
                )
            );
            ?>

        </div>

    </div>
</div>

