<?php if ($this->pageCount):  ?>
		<?php 
						
			if(!empty($this->lettre)){
				$url = $this->url($this->route).'?letter='.$this->lettre.'&';
			}elseif (!empty($this->critere) && !empty($this->mot_cle)){
				$url = $this->url($this->route).'?critere='.$this->critere.'&mot_cle='.$this->mot_cle.'&';
			}else{
				$url = $this->url($this->route).'?';
			}
		?>
        <div>
            <ul class="pagination">
                <!-- first page link -->
                <?php if (isset($this->previous)): ?>
                    <li>
                        <a href="<?php echo $url; ?>page=1">
                            <<
                        </a>
                    </li>
                <?php else: ?>
                    <li class="disabled">
                        <a href="#">
                            <<
                        </a>
                    </li>
                <?php endif; ?>
                <!-- Previous page link -->
                <?php if (isset($this->previous)): ?>
                    <li>
                        <a href="<?php echo $url;?>page=<?php echo $this->previous; ?>">
                            <
                        </a>
                    </li>
                <?php else: ?>
                    <li class="disabled">
                        <a href="#">
                            <
                        </a>
                    </li>
                <?php endif; ?>
                <!-- Numbered page links -->
                <?php foreach ($this->pagesInRange as $page): ?>
                    <?php if ($page != $this->current): ?>
                        <li>
                            <a href="<?php echo $url;?>page=<?php echo $page; ?>">
                                <?php echo $page; ?>
                            </a>
                        </li>
                    <?php else: ?>
                        <li class="active">
                            <a href="#"><?php echo $page; ?></a>
                        </li>
                    <?php endif; ?>
                <?php endforeach; ?>

                <!-- Next page link -->
                <?php if (isset($this->next)): ?>
                    <li>
                        <a href="<?php echo $url;?>page=<?php echo $this->next; ?>">
                            >
                        </a>
                    </li>
                <?php else: ?>
                    <li class="disabled">
                        <a href="#">
                            >
                        </a>
                    </li>
                <?php endif; ?>
                <!-- last page link -->
                <?php if (isset($this->next)): ?>
                    <li>
                        <a href="<?php echo $url;?>page=<?php echo $this->pageCount; ?>">
                            >>
                        </a>
                    </li>
                <?php else: ?>
                    <li class="disabled">
                        <a href="#">
                            >>
                        </a>
                    </li>
                <?php endif; ?>
            </ul>
        </div>
<?php endif; ?>