<?php if ($this->pageCount):  ?>

        <div>
            <ul class="pagination">
                <!-- first page link -->
                <?php if (isset($this->previous)): ?>
                    <li>
                        <a href="<?php echo $this->url($this->route); ?>/show?page=1">
                            <<
                        </a>
                    </li>
                <?php else: ?>
                    <li class="disabled">
                        <a href="#">
                            <<
                        </a>
                    </li>
                <?php endif; ?>
                <!-- Previous page link -->
                <?php if (isset($this->previous)): ?>
                    <li>
                        <a href="<?php echo $this->url($this->route); ?>/show?page=<?php echo $this->previous; ?>">
                            <
                        </a>
                    </li>
                <?php else: ?>
                    <li class="disabled">
                        <a href="#">
                            <
                        </a>
                    </li>
                <?php endif; ?>
                <!-- Numbered page links -->
                <?php foreach ($this->pagesInRange as $page): ?>
                    <?php if ($page != $this->current): ?>
                        <li>
                            <a href="<?php echo $this->url($this->route);?>/show?page=<?php echo $page; ?>">
                                <?php echo $page; ?>
                            </a>
                        </li>
                    <?php else: ?>
                        <li class="active">
                            <a href="#"><?php echo $page; ?></a>
                        </li>
                    <?php endif; ?>
                <?php endforeach; ?>

                <!-- Next page link -->
                <?php if (isset($this->next)): ?>
                    <li>
                        <a href="<?php echo $this->url($this->route);?>/show?page=<?php echo $this->next; ?>">
                            >
                        </a>
                    </li>
                <?php else: ?>
                    <li class="disabled">
                        <a href="#">
                            >
                        </a>
                    </li>
                <?php endif; ?>
                <!-- last page link -->
                <?php if (isset($this->next)): ?>
                    <li>
                        <a href="<?php echo $this->url($this->route);?>/show?page=<?php echo $this->pageCount; ?>">
                            >>
                        </a>
                    </li>
                <?php else: ?>
                    <li class="disabled">
                        <a href="#">
                            >>
                        </a>
                    </li>
                <?php endif; ?>
            </ul>
        </div>
<?php endif; ?>