<?php echo 'jesuis la' ?>
<?php echo $this->form()->openTag($form) ?>
    <dl class="zend_form">
        <?php foreach ($form as $element): ?>
            <?php if ($element->getLabel() != null && !$element instanceof Zend\Form\Element\Button): ?>
                <dt><?php echo $this->formLabel($element) ?></dt>
            <?php endif ?>
            <?php if (!$element instanceof Zend\Form\Element\Button): ?>
            <dd><?php echo $this->formInput($element) . $this->formElementErrors($element) ?></dd> 
            <?php endif ?>           
        <?php endforeach ?>
        <dd><?php echo $this->formButton($form->get('submit')) ?></dd>
    </dl>
<?php if ($this->redirect): ?>
    <input type="hidden" name="redirect" value="<?php echo $this->redirect ?>">
<?php endif ?>
<?php echo $this->form()->closeTag() ?>